version: 0.0
os: linux
files:
  - source: /
    destination: /src/Rebus
hooks:
  BeforeInstall:
    - location: /src/Rebus/Scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /src/Rebus/Scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /src/Rebus/Scripts/stop.sh
      timeout: 300
      runas: root
