version: '3'

services:
    rebusadmin:
        build:
            context: .
            dockerfile: RebusAdmin/Dockerfile
        ports:
            - "5003:5003"
        expose:
            - "5003"
        links:
            - rebusneo
    rebusneo:
        build:
            context: .
            dockerfile: RebusNeo/Dockerfile
        ports:
            - "5002:5002"
        expose:
            - "5002"
        links:
            - "rebuscore"
    rebuscore:
        build:
            context: .
            dockerfile: RebusCore/Dockerfile
        ports:
            - "5001:5001"
        expose:
            - "5001"
        links:
            - neo4j